CU_GIVE            = 'give [player] <block id> <count>'

KICK_SURVCPE       = 'Your client does not support required CPE exts.'
KICK_IGNORE        = 'Your client seems to be ignoring the setBlockPermission packet.'

CMD_GIVE           = '%d %s block(-s) given to &a%s'
CMD_CRAFTSUCC      = '%d block(-s) of %s crafted'
CMD_LCRAFT         = 'You need more %s to craft %d %s'
CMD_CANTCRAFT      = 'Selected block can\'t be crafted'
CMD_CRAFTHELP      = 'Open inventory and choose block to craft'
CMD_CRAFTQUIT      = 'Quit without crafting'
CMD_CRAFTHELP2     = 'To craft this block type /craft 1 or /craft <count>'
CMD_CRAFTGOD       = 'You can\'t craft things in god mode'
CMD_CRAFTNEG       = 'Blocks count can not be less than 1'
CMD_CRAFTTOOMANY   = 'You can\'t take more than 64 blocks of %s'
CMD_CRAFTRECIPE    = 'Recipe: %s to craft %d %s'
CMD_DROPTOOFAR     = 'This player is too far away from you'
CMD_DROPSUCCP      = 'Dropped %d %s blocks to %s'
CMD_DROPSUCC       = 'Dropped %d %s blocks'
CMD_GOD            = 'Godmode %s for &a%s&f'
CMD_HEAL           = 'Player &a%s&f healed'
CMD_TIMENOW        = 'Time in &a%s&f now is: %d'
CMD_TIMESTART      = 'Time resumed'
CMD_TIMESTOP       = 'Time is frozen'
CMD_HOMESET        = 'You have successfully set your new home'
CMD_HOMENF         = 'Home not found'

MESG_NOTOOL        = 'You don\'t have this tool in inventory'
MESG_NODMG         = 'This player cannot be damaged'
MESG_NOTENOUGH     = 'Not enough blocks'

SURV_OXYGEN        = 'Oxygen: %.1f'
SURV_KILL          = 'Player %s killed by %s.'
SURV_MINING        = 'Mining block: %d%%...'
